services:
  server-php-ex2ev:
    container_name: servidor_php_ex2ev
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    stdin_open: true
    links:
      - mariadb-server-ex2ev
    ports:
      - "8050:8000"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - project_network

  mariadb-server-ex2ev:
    container_name: servidor_db_ex2ev
    image: mariadb
    ports:
      - "3350:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - project_network

volumes:
  db_mysql:

networks:
  project_network: